"""Turkish SHORT-FORM citation cases for the cross-language parity fixture.

Why this module exists
----------------------
``evals/fixtures/reference_parity.json`` is the ONE artefact that pins
``legal_reference/parser.py`` (Python) and
``control-plane/src/retrieval/referenceParser.ts`` (TypeScript) to the same
behaviour; it is regenerated by ``scripts/gen_reference_fixtures.py``. W14/B-38
adds Turkish anaphoric ("short form") citations to both parsers, and those
cases have to live in the fixture or the pin is silently incomplete.

The cases are kept HERE, next to the parser they describe, rather than inline
in the generator, so that:

  * the generator only needs a three-line change to include them (see the
    integration request in ``docs/implementation/waves/W14-L-SOURCES.md``), and
  * a future edit to the short-form patterns and a future edit to their
    expectations sit in the same directory and are reviewed together.

Shape
-----
``SHORT_FORM_CASES`` is a tuple of dicts with exactly the fields
``scripts/gen_reference_fixtures.py``'s ``Case`` dataclass takes:

    {"name", "group", "description", "text", "expect"}

``expect`` is the HAND-WRITTEN legal expectation: an ordered tuple of
``(kind, {field: value})`` pairs. The generator refuses to write the fixture
unless the live Python parser satisfies every one of them, so the JSON can
never record a regression as the new truth.

The "belirsiz" rule
-------------------
A short form whose target cannot be resolved from the surrounding text keeps
EVERY identity field ``None``. Two cases below assert exactly that, because a
short form promoted to a full citation would be the product inventing an
authority — the one failure this system exists to prevent.
"""

from __future__ import annotations

# Kind constants, mirroring the generator's own short aliases.
_L = "legislation"
_A = "article"
_C = "court_decision"
_S = "short_form"


SHORT_FORM_CASES: tuple = (
    {
        "name": "shortform_repeated_article_resolves_from_context",
        "group": "short_form",
        "description": (
            "The form a Turkish brief actually uses: the law is named once, "
            "then its articles are repeated bare. 'Aynı Kanunun 352 nci "
            "maddesi' and the later plain 'm. 352' both resolve to TBK (6098) "
            "and are marked as SHORT FORMS, not as fresh full citations."
        ),
        "text": (
            "TBK m. 315 uyarınca ihtar çekilmiştir. Aynı Kanunun 352 nci "
            "maddesi de uygulanır. Sonradan m. 352 tekrar tartışılmıştır."
        ),
        "expect": (
            (_L, {"legislation_no": "6098", "abbreviation": "TBK"}),
            (_A, {"article_no": "315"}),
            (_S, {"article_no": "352", "legislation_no": "6098",
                  "canonical_name": "Türk Borçlar Kanunu"}),
            (_S, {"article_no": "352", "legislation_no": "6098"}),
        ),
    },
    {
        "name": "shortform_yukarida_anilan_keeps_full_citation",
        "group": "short_form",
        "description": (
            "'Yukarıda anılan TBK m. 315' is a short-form PHRASE around a "
            "citation that is nevertheless complete. It must still parse as "
            "legislation + article; the marker must not degrade it."
        ),
        "text": "Yukarıda anılan TBK m. 315 hükmü uygulanır.",
        "expect": (
            (_L, {"legislation_no": "6098", "abbreviation": "TBK"}),
            (_A, {"article_no": "315", "article_kind": "madde"}),
        ),
    },
    {
        "name": "shortform_ayni_kanunun_after_full_name",
        "group": "short_form",
        "description": (
            "'aynı Kanunun 345 inci maddesi' after the law was written out in "
            "full resolves to that law."
        ),
        "text": (
            "6098 sayılı Türk Borçlar Kanunu m. 344 uygulanır; aynı Kanunun "
            "345 inci maddesi de dikkate alınır."
        ),
        "expect": (
            (_L, {"legislation_no": "6098"}),
            (_A, {"article_no": "344"}),
            (_S, {"article_no": "345", "legislation_no": "6098"}),
        ),
    },
    {
        "name": "shortform_decision_anilan_karar",
        "group": "short_form",
        "description": (
            "'Anılan karar' and 'aynı yönde' refer back to the decision cited "
            "just before; both carry that decision's E./K. pair, court and "
            "chamber. Without this, an opposing brief's back-references are "
            "silently missing from the citation audit."
        ),
        "text": (
            "Yargıtay 3. HD E. 2021/123, K. 2022/456 kararı incelendi. "
            "Anılan karar ile aynı yönde başka kararlar da vardır."
        ),
        "expect": (
            (_C, {"docket_no": "2021/123", "decision_no": "2022/456",
                  "court": "YARGITAY", "chamber": "3. HD"}),
            (_S, {"docket_no": "2021/123", "decision_no": "2022/456",
                  "court": "YARGITAY", "chamber": "3. HD"}),
            (_S, {"docket_no": "2021/123", "decision_no": "2022/456"}),
        ),
    },
    {
        "name": "shortform_decision_without_antecedent_is_belirsiz",
        "group": "short_form",
        "description": (
            "A back-reference with NOTHING to refer back to falls into the "
            "'belirsiz' bucket: every identity field stays null. It says a "
            "citation is there, never WHICH one."
        ),
        "text": "Anılan kararda belirtildiği üzere zamanaşımı işlemez.",
        "expect": (
            (_S, {"docket_no": None, "decision_no": None, "court": None,
                  "legislation_no": None, "article_no": None}),
        ),
    },
    {
        "name": "shortform_agk_abbreviation_is_belirsiz",
        "group": "short_form",
        "description": (
            "'agk.' (anılan geçen karar) with no antecedent is recognized as "
            "a short form and left unresolved."
        ),
        "text": "agk. uyarınca istem reddedilmiştir.",
        "expect": (
            (_S, {"docket_no": None, "decision_no": None,
                  "legislation_no": None}),
        ),
    },
    {
        "name": "shortform_anaphoric_article_without_antecedent_is_belirsiz",
        "group": "short_form",
        "description": (
            "'Mezkûr Yönetmeliğin 12 nci maddesi' with no instrument named "
            "anywhere before it resolves to NOTHING. The article number is "
            "kept, the law is not invented."
        ),
        "text": "Mezkûr Yönetmeliğin 12 nci maddesi uygulanır.",
        "expect": (
            (_S, {"article_no": "12", "legislation_no": None,
                  "canonical_name": None}),
        ),
    },
    {
        "name": "shortform_marker_words_alone_are_not_citations",
        "group": "short_form",
        "description": (
            "'aynı' and 'karar' on their own are ordinary Turkish words: only "
            "the fixed marker phrases count, so plain prose yields nothing."
        ),
        "text": "Taraflar aynı görüşte değildir; mahkeme karar verecektir.",
        "expect": (),
    },
)
