/**
 * Cross-language offset-policy parity checks (TypeScript side).
 *
 * Reads control-plane/fixtures/offset_policy.json (generated by
 * scripts/gen_offset_fixtures.py, validated in Python by
 * tests/contracts/test_offset_policy.py) and proves that validateEvidence
 * implements the canonical policy: Unicode CODE POINT offsets into NFC text.
 *
 * The `utf16_differs` cases are the must-fail witnesses: for them, naive
 * UTF-16 slicing (String.prototype.slice) returns the WRONG text, so a
 * UTF-16-indexed validator could not pass this suite.
 */

import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import type { EvidenceRef } from "../src/evidence/types.js";
import {
  codePointLength,
  codePointSlice,
  sha256HexUtf8,
  validateEvidence,
} from "../src/verification/validator.js";

interface FixtureCase {
  name: string;
  description: string;
  canonical_text: string;
  start: number;
  end: number;
  expected_quote: string;
  expected_quote_sha256: string;
  expected_content_sha256: string;
  utf16_start: number;
  utf16_end: number;
  utf16_differs: boolean;
  nfd_source_text?: string;
}

interface Fixture {
  policy: { offset_unit: string; normal_form: string; hash: string };
  cases: FixtureCase[];
}

const fixturePath = join(
  dirname(fileURLToPath(import.meta.url)),
  "..",
  "fixtures",
  "offset_policy.json",
);
const fixture = JSON.parse(readFileSync(fixturePath, "utf8")) as Fixture;

function evidenceFor(c: FixtureCase, overrides: Partial<EvidenceRef> = {}): EvidenceRef {
  return {
    evidenceId: `ev-${c.name}`,
    documentId: "doc-1",
    documentVersionId: "docv-1",
    chunkId: "chunk-1",
    source: "FIXTURE",
    sourceUrl: "https://example.invalid/fixture",
    title: c.name,
    locator: { startChar: c.start, endChar: c.end },
    quote: c.expected_quote,
    quoteSha256: c.expected_quote_sha256,
    contentSha256: c.expected_content_sha256,
    retrievedAt: "2026-08-26T00:00:00Z",
    ...overrides,
  };
}

describe("offset policy fixture header", () => {
  it("declares the canonical policy", () => {
    expect(fixture.policy.offset_unit).toBe("unicode_code_points");
    expect(fixture.policy.normal_form).toBe("NFC");
    expect(fixture.policy.hash).toBe("sha256_hex_over_utf8");
    expect(fixture.cases.length).toBeGreaterThanOrEqual(8);
  });

  it("contains at least one UTF-16 must-fail witness", () => {
    expect(fixture.cases.some((c) => c.utf16_differs)).toBe(true);
  });
});

describe.each(fixture.cases)("fixture case: $name", (c) => {
  it("validateEvidence accepts the canonical evidence", () => {
    expect(validateEvidence(evidenceFor(c), c.canonical_text)).toEqual({ ok: true });
  });

  it("codePointSlice matches the expected quote and Python slicing", () => {
    expect(codePointSlice(c.canonical_text, c.start, c.end)).toBe(c.expected_quote);
  });

  it("hashes are SHA-256 hex over UTF-8 (parity with hashlib)", () => {
    expect(sha256HexUtf8(c.expected_quote)).toBe(c.expected_quote_sha256);
    expect(sha256HexUtf8(c.canonical_text)).toBe(c.expected_content_sha256);
  });
});

describe("UTF-16 must-fail witnesses", () => {
  const witnesses = fixture.cases.filter((c) => c.utf16_differs);

  it.each(witnesses)(
    "$name: naive String.prototype.slice returns the WRONG text at code point offsets",
    (c) => {
      // This is what a UTF-16-indexed implementation would produce.
      const naive = c.canonical_text.slice(c.start, c.end);
      expect(naive).not.toBe(c.expected_quote);
      // ...while the code-point implementation is correct:
      expect(codePointSlice(c.canonical_text, c.start, c.end)).toBe(c.expected_quote);
    },
  );

  it.each(witnesses)(
    "$name: evidence carrying the naive UTF-16 slice as its quote is rejected",
    (c) => {
      const naive = c.canonical_text.slice(c.start, c.end);
      const result = validateEvidence(evidenceFor(c, { quote: naive }), c.canonical_text);
      expect(result).toEqual({ ok: false, reason: "QUOTE_OFFSET_MISMATCH" });
    },
  );

  it.each(witnesses)(
    "$name: UTF-16 unit offsets differ from code point offsets as recorded",
    (c) => {
      expect(c.utf16_start !== c.start || c.utf16_end !== c.end).toBe(true);
      // Cross-check the recorded UTF-16 offsets against JS string indexing:
      // the UTF-16 length of the code-point prefix IS the utf16 offset.
      const prefix = codePointSlice(c.canonical_text, 0, c.start);
      expect(prefix.length).toBe(c.utf16_start);
      const upToEnd = codePointSlice(c.canonical_text, 0, c.end);
      expect(upToEnd.length).toBe(c.utf16_end);
    },
  );
});

describe("NFC normalization policy", () => {
  const nfdCases = fixture.cases.filter((c) => c.nfd_source_text !== undefined);

  it("fixture includes an NFD-input case", () => {
    expect(nfdCases.length).toBeGreaterThan(0);
  });

  it.each(nfdCases)(
    "$name: validator normalizes NFD input to NFC before slicing/hashing",
    (c) => {
      const nfd = c.nfd_source_text as string;
      expect(nfd).not.toBe(c.canonical_text);
      expect(codePointLength(nfd)).not.toBe(codePointLength(c.canonical_text));
      // Offsets/hashes were computed against NFC — handing the validator the
      // NFD spelling of the same canonical text must still validate.
      expect(validateEvidence(evidenceFor(c), nfd)).toEqual({ ok: true });
    },
  );
});
