/**
 * Cross-language parity: the TypeScript reference parser must reproduce the
 * shared fixture EXACTLY.
 *
 * `evals/fixtures/reference_parity.json` is generated by
 * `scripts/gen_reference_fixtures.py` from the Python parser, with a
 * hand-written legal expectation attached to every case. The Python side
 * validates the same file in `tests/contracts/test_parser_parity.py`, so a
 * change to either implementation that is not mirrored in the other breaks
 * CI in both languages.
 *
 * Regenerate with:
 *   .venv/Scripts/python.exe scripts/gen_reference_fixtures.py
 */
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import { normalizeTurkishSearch } from "../src/retrieval/normalize.js";
import {
  LAW_ABBREVIATIONS,
  parseReferences,
  type ParsedReference,
} from "../src/retrieval/referenceParser.js";

interface FixtureRef {
  kind: string;
  raw: string;
  span: [number, number];
  legislation_no: string | null;
  article_no: string | null;
  docket_no: string | null;
  decision_no: string | null;
  year: number | null;
  name: string | null;
  article_kind: string | null;
  paragraph: string | null;
  clause: string | null;
  abbreviation: string | null;
  canonical_name: string | null;
  mulga: boolean;
  court: string | null;
  chamber: string | null;
  docket_kind: string | null;
  decision_date: string | null;
  rg_date: string | null;
  rg_no: string | null;
}

interface FixtureCase {
  name: string;
  group: string;
  description: string;
  text: string;
  normalized: string;
  expected: FixtureRef[];
}

interface FixtureAbbreviation {
  key: string;
  legislation_no: string;
  canonical_name: string;
  mulga: boolean;
  variants: string[];
}

interface Fixture {
  policy: { fields: string[]; offset_unit: string; normal_form: string; bmp_only: boolean };
  abbreviations: FixtureAbbreviation[];
  cases: FixtureCase[];
}

const FIXTURE_PATH = join(
  dirname(fileURLToPath(import.meta.url)),
  "..",
  "..",
  "evals",
  "fixtures",
  "reference_parity.json",
);

const FIXTURE = JSON.parse(readFileSync(FIXTURE_PATH, "utf8")) as Fixture;

/** Language-neutral form of a parsed reference (mirrors `serialize()`). */
function serialize(ref: ParsedReference): FixtureRef {
  const span = ref.span ?? [0, 0];
  return {
    kind: ref.kind,
    raw: ref.raw,
    span: [span[0], span[1]],
    legislation_no: ref.legislationNo ?? null,
    article_no: ref.articleNo ?? null,
    docket_no: ref.docketNo ?? null,
    decision_no: ref.decisionNo ?? null,
    year: ref.year ?? null,
    name: ref.name ?? null,
    article_kind: ref.articleKind ?? null,
    paragraph: ref.paragraph ?? null,
    clause: ref.clause ?? null,
    abbreviation: ref.abbreviation ?? null,
    canonical_name: ref.canonicalName ?? null,
    mulga: ref.mulga === true,
    court: ref.court ?? null,
    chamber: ref.chamber ?? null,
    docket_kind: ref.docketKind ?? null,
    decision_date: ref.decisionDate ?? null,
    rg_date: ref.rgDate ?? null,
    rg_no: ref.rgNo ?? null,
  };
}

describe("reference parity fixture", () => {
  it("carries a large corpus (the whole point of the cross-language pin)", () => {
    expect(FIXTURE.cases.length).toBeGreaterThanOrEqual(70);
    expect(FIXTURE.policy.normal_form).toBe("NFC");
    expect(FIXTURE.policy.bmp_only).toBe(true);
  });

  it("covers every reference family and the false-positive guards", () => {
    const groups = new Set(FIXTURE.cases.map((c) => c.group));
    for (const group of ["legislation", "abbreviation", "article", "court", "gazette", "guard", "multi"]) {
      expect(groups.has(group), `missing fixture group ${group}`).toBe(true);
    }
    // Guards must actually assert emptiness, not merely exist.
    const guards = FIXTURE.cases.filter((c) => c.group === "guard");
    expect(guards.length).toBeGreaterThanOrEqual(10);
    for (const guard of guards) {
      expect(guard.expected, guard.name).toEqual([]);
    }
  });

  it("is BMP-only, so UTF-16 and code point offsets coincide", () => {
    for (const testCase of FIXTURE.cases) {
      for (const char of testCase.text) {
        expect(char.codePointAt(0) ?? 0, testCase.name).toBeLessThanOrEqual(0xffff);
      }
    }
  });
});

describe("abbreviation table parity", () => {
  it("mirrors the Python table exactly (key, number, name, mülga, variants)", () => {
    const actual = LAW_ABBREVIATIONS.map((entry) => ({
      key: entry.key,
      legislation_no: entry.legislationNo,
      canonical_name: entry.canonicalName,
      mulga: entry.mulga,
      variants: [...entry.variants],
    }));
    expect(actual).toEqual(FIXTURE.abbreviations);
  });

  it("covers the abbreviations Turkish lawyers actually type", () => {
    const byKey = new Map(FIXTURE.abbreviations.map((a) => [a.key, a]));
    const required: Array<[string, string]> = [
      ["TCK", "5237"],
      ["CMK", "5271"],
      ["TBK", "6098"],
      ["TMK", "4721"],
      ["HMK", "6100"],
      ["İİK", "2004"],
      ["TTK", "6102"],
      ["VUK", "213"],
      ["İYUK", "2577"],
      ["KVKK", "6698"],
      ["İŞK", "4857"],
      ["ANAYASA", "2709"],
      ["AATUHK", "6183"],
      ["KDVK", "3065"],
      ["GVK", "193"],
      ["KVK", "5520"],
      ["SSGSSK", "5510"],
      ["İMARK", "3194"],
      ["TKHK", "6502"],
      ["FSEK", "5846"],
      ["SERPK", "6362"],
      ["KABK", "5326"],
      ["CGTİHK", "5275"],
      ["ETCK", "765"],
      ["HUMK", "1086"],
    ];
    for (const [key, no] of required) {
      expect(byKey.get(key)?.legislation_no, key).toBe(no);
    }
    // Historical instruments must be flagged, never silently current.
    for (const key of ["ETCK", "HUMK", "ETTK", "EBK", "CMUK"]) {
      expect(byKey.get(key)?.mulga, key).toBe(true);
    }
  });
});

describe("parseReferences matches the shared fixture", () => {
  for (const testCase of FIXTURE.cases) {
    it(`${testCase.name}: ${testCase.description}`, () => {
      const actual = parseReferences(testCase.text).map(serialize);
      expect(actual).toEqual(testCase.expected);
    });
  }

  it("slices every span back to its raw text", () => {
    for (const testCase of FIXTURE.cases) {
      for (const ref of parseReferences(testCase.text)) {
        const span = ref.span ?? [0, 0];
        expect(testCase.text.slice(span[0], span[1]), testCase.name).toBe(ref.raw);
      }
    }
  });

  it("is re-entrant: parsing twice yields identical results", () => {
    for (const testCase of FIXTURE.cases) {
      expect(parseReferences(testCase.text)).toEqual(parseReferences(testCase.text));
    }
  });
});

describe("normalizeTurkishSearch matches the shared fixture", () => {
  it("agrees with the Python normalizer on every corpus input", () => {
    for (const testCase of FIXTURE.cases) {
      expect(normalizeTurkishSearch(testCase.text), testCase.name).toBe(testCase.normalized);
    }
  });

  it("is idempotent on every corpus input", () => {
    for (const testCase of FIXTURE.cases) {
      expect(normalizeTurkishSearch(testCase.normalized), testCase.name).toBe(
        testCase.normalized,
      );
    }
  });
});
